### ISSUE TITLE
Permissions too broad

### ISSUE THREAD

**Issue by openscript** [hoppscotch/hoppscotch-extension#70]
Great project! Thank you very much!

My question is regarding to the Firefox Extension. Isn't it enough to only ask for permission to read all data of the hoppscotch.io domain?

**Comment by AndrewBastin** [comment]
Hi there, thanks for your remarks! Means a lot!

First of all, we follow the WebExtension spec as much as possible and hence, the Chrome extension and the Firefox extension actually are just the same thing just packaged differently for each.

The reason why we have broader permissions is because we have received word that there are people/companies using Hoppscotch but do not use the official hoppscotch.io instance and instead self-host their own instance of Hoppscotch. If you click on the Hoppscotch icon on your browser toolbar it will open up a popup which lets you add given domains to the extension's allow list to provide access to. Only the domains defined in the extension's white list are ever given access to. Since we can't be sure which domains need access to the Hoppscotch Extension (because self-hosting), we wanted to provision that option.

Eventually we will be migrating to [Web Extension Manifest v3](https://developer.chrome.com/docs/extensions/mv3/intro/) which will provide opt-in permissions in the browser side. But until then we will be sticking on to this solution for now.


Hope this answers your concern!
I am closing this issue but still feel free to extend anymore concerns here!

Happy hacking! :)
